/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#F8FAF8',
        foreground: '#1F2937',
        border: '#E6ECE7',
        input: '#E6ECE7',
        ring: '#2F6B44',
        card: '#FFFFFF',
        'card-foreground': '#1F2937',
        muted: '#9CA3AF',
        'muted-foreground': '#6B7280',
        success: '#16A34A',
        'success-foreground': '#FFFFFF',
        'success-soft': '#F0FDF4',
        warning: '#F59E0B',
        'warning-foreground': '#FFFFFF',
        'warning-soft': '#FFFBEB',
        danger: '#DC2626',
        'danger-foreground': '#FFFFFF',
        'danger-soft': '#FEF2F2',
        sky: '#1796CF',
        'sky-foreground': '#FFFFFF',
        'sky-soft': '#E8F6FF',
        error: '#DC2626',
        'error-container': '#FEF2F2',
        'on-error': '#FFFFFF',
        'on-error-container': '#7F1D1D',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#14532D',
        'on-primary-fixed': '#052E16',
        'on-primary-fixed-variant': '#166534',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#14532D',
        'on-surface': '#1F2937',
        'on-surface-variant': '#6B7280',
        outline: '#9CA3AF',
        'outline-variant': '#E6ECE7',
        primary: '#2F6B44',
        'primary-hover': '#245739',
        'primary-container': '#3D8B5A',
        'primary-fixed': '#86EFAC',
        'primary-fixed-dim': '#4ADE80',
        secondary: '#16A34A',
        'secondary-container': '#DCFCE7',
        surface: '#FFFFFF',
        'surface-secondary': '#F3F7F4',
        'surface-bright': '#FFFFFF',
        'surface-container': '#F3F7F4',
        'surface-container-high': '#E6ECE7',
        'surface-container-highest': '#D1D9D3',
        'surface-container-low': '#F3F7F4',
        'surface-container-lowest': '#FFFFFF',
        'surface-dim': '#E6ECE7',
        'surface-variant': '#E6ECE7',
        tertiary: '#F59E0B',
        'tertiary-container': '#FEF3C7',
      },
      fontFamily: {
        sans: ['Manrope', 'Segoe UI', 'sans-serif'],
        display: ['Manrope', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3rem', { lineHeight: '1.2', fontWeight: '800' }],
        'display-lg-mobile': ['2.25rem', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-md': ['1.25rem', { lineHeight: '1.4', fontWeight: '700' }],
        'body-lg': ['1rem', { lineHeight: '1.6', fontWeight: '500' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-uppercase': ['0.75rem', { lineHeight: '1', fontWeight: '700', letterSpacing: '0.08em' }],
      },
      spacing: {
        'section-gap': '5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        gutter: '1.25rem',
        unit: '0.5rem',
      },
      maxWidth: {
        'container-max-width': '1400px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1rem',
        organic: '1rem',
        pill: '9999px',
        card: '16px',
        image: '14px',
        btn: '10px',
        field: '12px',
        modal: '16px',
        dropdown: '12px',
      },
      boxShadow: {
        apple: '0 2px 12px rgba(31, 41, 55, 0.04)',
        'apple-md': '0 8px 24px rgba(31, 41, 55, 0.08)',
        card: '0 2px 12px rgba(31, 41, 55, 0.04)',
        'card-hover': '0 12px 32px rgba(47, 107, 68, 0.10)',
        panel: '0 2px 12px rgba(31, 41, 55, 0.06)',
        glass: '0 8px 32px rgba(47, 107, 68, 0.06)',
      },
      transitionDuration: {
        DEFAULT: '200ms',
      },
      animation: {
        blob: 'blob 7s infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'scale-up': 'scaleUp 0.3s ease-out forwards',
      },
      keyframes: {
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        scaleUp: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
