/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f7fbf8',
        foreground: '#16201b',
        border: '#d5e3db',
        input: '#c8d8cf',
        ring: '#146c43',
        card: '#ffffff',
        'card-foreground': '#16201b',
        muted: '#edf4ef',
        'muted-foreground': '#5a675f',
        success: '#1f9d55',
        'success-foreground': '#ffffff',
        'success-soft': '#e9f7ef',
        warning: '#f2a51a',
        'warning-foreground': '#7c2d12',
        'warning-soft': '#fff7e6',
        danger: '#d64c3f',
        'danger-foreground': '#ffffff',
        'danger-soft': '#feeceb',
        sky: '#1796cf',
        'sky-foreground': '#ffffff',
        'sky-soft': '#e8f6ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#00422b',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714e',
        'on-surface': '#16201b',
        'on-surface-variant': '#4b5b52',
        outline: '#708277',
        'outline-variant': '#c0d1c7',
        primary: '#146c43',
        'primary-container': '#1f9d55',
        'primary-fixed': '#87efb9',
        'primary-fixed-dim': '#56d892',
        secondary: '#0f7a52',
        'secondary-container': '#b8f2d0',
        surface: '#f7fbf8',
        'surface-bright': '#fbfdfb',
        'surface-container': '#e8f1eb',
        'surface-container-high': '#e2ebe5',
        'surface-container-highest': '#d6e3dc',
        'surface-container-low': '#f1f6f3',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dbe5df',
        'surface-variant': '#d5e3db',
        tertiary: '#9e5a2f',
        'tertiary-container': '#f7b786',
      },
      fontFamily: {
        sans: ['"Be Vietnam Pro"', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3rem', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg-mobile': ['2.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.6' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'label-uppercase': ['0.75rem', { lineHeight: '1', fontWeight: '700', letterSpacing: '0.08em' }],
      },
      spacing: {
        'section-gap': '5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        gutter: '1.25rem',
        unit: '0.5rem',
      },
      maxWidth: {
        'container-max-width': '1400px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        'apple': '0px 4px 20px rgba(0, 0, 0, 0.04)',
        'apple-md': '0px 8px 32px rgba(0, 0, 0, 0.08)',
        card: "0 10px 30px rgba(15, 23, 42, 0.05)",
        panel: "0 2px 12px rgba(15, 23, 42, 0.06)",
      },
      animation: {
        blob: "blob 7s infinite",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "scale-up": "scaleUp 0.3s ease-out forwards",
      },
      keyframes: {
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        scaleUp: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        }
      },
    },
  },
  plugins: [],
};
