/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#F4F9F5', // Soft Sage
        foreground: '#1B2623', // Dark Slate
        border: '#D5E3DB',
        input: '#C8D8CF',
        ring: '#2A5A3B',
        card: '#FDFDFD', // Warm White
        'card-foreground': '#1B2623',
        muted: '#E8F1EB',
        'muted-foreground': '#4B5B52',
        success: '#2A5A3B',
        'success-foreground': '#FFFFFF',
        'success-soft': '#E9F7EF',
        warning: '#E07A5F', // Terracotta
        'warning-foreground': '#FFFFFF',
        'warning-soft': '#FFF7E6',
        danger: '#D64C3F',
        'danger-foreground': '#FFFFFF',
        'danger-soft': '#FEECEB',
        sky: '#1796CF',
        'sky-foreground': '#FFFFFF',
        'sky-soft': '#E8F6FF',
        error: '#BA1A1A',
        'error-container': '#FFDAD6',
        'on-error': '#FFFFFF',
        'on-error-container': '#93000A',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#00422B',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#00714E',
        'on-surface': '#1B2623',
        'on-surface-variant': '#4B5B52',
        outline: '#708277',
        'outline-variant': '#C0D1C7',
        primary: '#2A5A3B',
        'primary-container': '#3E7D56',
        'primary-fixed': '#87EFB9',
        'primary-fixed-dim': '#56D892',
        secondary: '#E07A5F',
        'secondary-container': '#FAD7CD',
        surface: '#F4F9F5',
        'surface-bright': '#FDFDFD',
        'surface-container': '#E8F1EB',
        'surface-container-high': '#E2EBE5',
        'surface-container-highest': '#D6E3DC',
        'surface-container-low': '#F1F6F3',
        'surface-container-lowest': '#FFFFFF',
        'surface-dim': '#DBE5DF',
        'surface-variant': '#D5E3DB',
        tertiary: '#9E5A2F',
        'tertiary-container': '#F7B786',
      },
      fontFamily: {
        sans: ['Inter', 'Segoe UI', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3rem', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg-mobile': ['2.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.6' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'label-uppercase': ['0.75rem', { lineHeight: '1', fontWeight: '700', letterSpacing: '0.08em' }],
      },
      spacing: {
        'section-gap': '5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        gutter: '1.25rem',
        unit: '0.5rem',
      },
      maxWidth: {
        'container-max-width': '1400px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "organic": "2rem",
        "pill": "9999px",
      },
      boxShadow: {
        'apple': '0px 4px 20px rgba(0, 0, 0, 0.04)',
        'apple-md': '0px 8px 32px rgba(0, 0, 0, 0.08)',
        card: "0 10px 30px rgba(15, 23, 42, 0.05)",
        panel: "0 2px 12px rgba(15, 23, 42, 0.06)",
      },
      animation: {
        blob: "blob 7s infinite",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "scale-up": "scaleUp 0.3s ease-out forwards",
      },
      keyframes: {
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        scaleUp: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        }
      },
    },
  },
  plugins: [],
};
